language: php
php:
  - 5.6
  - 7.0
install:
 - composer self-update
 - composer install --no-interaction --dev
matrix:
  allow_failures:
    - php: 7.0
before_script:
 - (cd public; echo \"\nStarting web server at http://localhost:8000 ...\n\"; php -S localhost:8000) &
script:
 - composer test
